### PR TITLE
Add windows-curses for support on windows

### LINKED ISSUE #1100: curses not available on windows
As noticed in the circus feedstock on conda-forge, circus uses [`curses`](https://docs.python.org/3/howto/curses.html) but it seems  `curses` [doesn't work on windows](https://ci.appveyor.com/project/conda-forge/circus-feedstock/builds/21074915) (?).

In [this issue](https://github.com/conda-forge/circus-feedstock/issues/7), it was mentioned that circus supports windows since version 0.12, so it seems like we are missing something.
How should we build the `circus` conda package for windows?

possible workarounds
 * https://github.com/zephyrproject-rtos/windows-curses
 * https://stackoverflow.com/a/41224335

Mentioning also the recipe maintainer @carlodri

### PR DESCRIPTION
**Pull request by ltalirz**
Fixes #1100.

 * Building on #1134 to add windows-curses dependency for support on windows
 * switch CI from travis to github actions, splitting different python versions into separate jobs (complete test suite run now takes <2 mins)
 * add CI runs on windows and macos
 * fix MANIFEST.in

See windows build at https://github.com/ltalirz/circus/runs/955260205

### CODE REVIEW

**Comment by ltalirz** [comment]
@biozz This is still a work in progress:

 * 3 tests on macos are failing
 * tests on windows "pass" but only because all tests are being skipped ;-)

Would you mind taking it from here?
I'll give you write access to my fork (otherwise, feel free to pull my branch and make a new PR).

**Comment by biozz** [comment]
@ltalirz sure, thank you for the kick-start! 

The config looks simple and easy to understand, the most difficult part will be to fix tests. And if anything goes south we can split it into several parts. 

I actually would prefer to have separate PRs for github actions and windows-related fixes. But that's okay, we can keep it as is.

**Comment by ltalirz** [comment]
> I actually would prefer to have separate PRs for github actions and windows-related fixes

I got the feeling as well after making the change.
I think it would probably be ok to merge the PR as-is (with the windows/macos builds failing).

If you think it's important to disable them until the tests pass, let me know and I can modify it @k4nar

**Comment by biozz** [comment]
@ltalirz well if we both agree that this PR has too much going on, could you please submit a separate one with proper branch name, topic and description? (it is ok to skip win and mac tests)

No offense, but I am all about clean commit history. I can take over if that is too much to ask.

**Comment by ltalirz** [comment]
Sure, here's a new one https://github.com/circus-tent/circus/pull/1137

**Pull request closed without merging**
