### PR TITLE
Actions on multiple watchers

### PR DESCRIPTION
**Pull request by oglu**
This is a rebase of #829

### CODE REVIEW

**Comment by oglu** [comment]
Any idea why circus-web hangs ?

**Comment by k4nar** [comment]
Well, it happens sometimes, I just restarted it.

**Comment by k4nar** [comment]
Ok, it was a random failure.

However, I think we should add some tests to this PR, as it's pretty big.

**Comment by oglu** [comment]
Can we keep it on hold then until we have a new release? I'd prefer to spend some time on removing any potential blockers for a new release. Could we have support for tornado 4 in that new release ?

**Comment by k4nar** [comment]
Tornado 4 support was merged a few minutes ago :) .

I'm ok for merging it know, as it has already been reviewed several times.

**Comment by k4nar** [comment]
Thanks @max0d41 and @oglu !

**Pull request merged**
