### PR TITLE
Dependencies: Remove `papa` and related functionality

### PR DESCRIPTION
**Pull request by sphuber**
The `papa` library provides a process kernel that `circus` allowed ot use through configuration. However, `papa` seems to be no longer maintained as its last release was in January 2016. Officially it only declares to be compatible up to Python 3.4. Apparently, so far it has still been working until Python 3.10 where it actually breaks. Since it is no longer maintained, we remove support for it from `circus`.

### CODE REVIEW

**Comment by biozz** [comment]
I don't mind the deleting `papa` as long as it is clearly stated in the changelog.

As for the code review, I see that there is also `PapaRedirector`, which can also be removed.

**Comment by sphuber** [comment]
Thanks for the review @biozz 

> I don't mind the deleting papa as long as it is clearly stated in the changelog.

Naturally. If we merge this, I propose we release it with `0.18.0` and clearly mention in the changelog as always.

> As for the code review, I see that there is also PapaRedirector, which can also be removed.

Good catch, have removed it.

I think I will leave this open over the weekend to give @k4nar a chance to chime in to see if this still needs to be kept in the end.

**Review by biozz — APPROVED** [review]

**Comment by k4nar** [comment]
I have no idea of how much (or if) papa is used. But do you think there would be a simple solution to make it optional instead?

cc @scottkmaxwell as you are the author of papa & its integration in Circus

**Comment by sphuber** [comment]
> But do you think there would be a simple solution to make it optional instead?

Not sure to be honest. The plugin touched the main code in quite a number of places. We could make the import statement in a try/except and probably update all conditionals everywhere to check whether `papa` is available. But we have to anyway disable the tests for Python 3.10 and any future versions since it is not compatible and tests will fail. Python 3.11 is also already out. So I would say that unless the package will be revived and see updates, there is little point to keeping it around. Providing support for it will be non-negligible.

**Comment by sphuber** [comment]
Not sure that we will be getting a response, so I will merge this.

**Pull request merged**
