### PR TITLE
stdin_socket

### LINKED ISSUE #975: Cannot place listening socket at fd=0 (fastcgi support)
The fastcgi protocol appears to require a single listening socket passed to the application and that this socket is positioned at file descriptor 0. (https://github.com/toshic/libfcgi/blob/master/doc/fcgi-spec.html#L227-L231). One way to specify this would be to create a new configurable property `stdin_socket` for a `watcher`, which provides the name of a socket which should be placed at at fd 0, while creating the `watcher`'s child processes. For example:
```
[watcher:example-watcher]
cmd = fcgi-binary-application-expecting-fd-0
use_sockets = True
warmup_delay = 0
numprocesses = 5
stdin_socket=fastcgi

[socket:fastcgi]
host = 0.0.0.0
port = 8000
blocking = true
```

In the example, `stdin_socket=fastcgi` references the socket named in the section `[socket:fastcgi]`, and tells circus that it should `dup2()` the socket to fd 0, during fork.

### PR DESCRIPTION
**Pull request by billygout**
@k4nar this resolves #975

### CODE REVIEW

**Comment by billygout** [comment]
Hi, @k4nar, I'm curious if you've taken a look at this...thanks

**Comment by k4nar** [comment]
I'm sorry, I'm struggling with our CI right now. I'll keep you posted when #984 is merged so that you can rebase.

**Comment by billygout** [comment]
Yeah, I figured. Looks like your up to good work :) thanks for the update

**Comment by k4nar** [comment]
@billygout : Okay, our tests are in far better shape now, even though we still have a few hiccups. Could you rebase this PR?

**Comment by billygout** [comment]
@k4nar Doing it...

**Comment by billygout** [comment]
@k4nar Trying to debug the travis build errors....

**Comment by billygout** [comment]
@k4nar, rebased and travis passes. There was an issue with python2.6 closing sockets before preexec function is called by Popen(). So, stdin_socket requires use_sockets to be set to True, which has the effect that all opened sockets remain open, not only the one specified with the stdin_socket option. Let me know if there is an issue, and if there is any other way you'd like to see this handled.

**Comment by k4nar** [comment]
As long as it's only an issue with Python 2.6 it doesn't bother me.

Thank you very much for your work :+1: .

**Comment by billygout** [comment]
@k4nar FYI, I found the python issue under which the ordering of closing fds and calling the preexec_fn was changed: http://bugs.python.org/issue18763
The change first arrived in 2.7.6 and the new behaviour is preserved all the way through python 3.5.

Have you considered removing python 2.6 as a travis target?

**Comment by k4nar** [comment]
Yeah, I've considered it, but I'm not sure if it's really necessary.

**Pull request merged**
