### PR TITLE
Lock tornado version to pre-5.0 and PyZMQ version to pre-17.0

### LINKED ISSUE #1059: Not compatible with Tornado 5
Hello,

I tried with the last master to launch a small executable like in Step by Step install
However I keep getting this error:

```
2018-03-14 22:17:45 circus[14844] [INFO] Starting master on pid 14844
2018-03-14 22:17:45 circus[14844] [INFO] sockets started
2018-03-14 22:17:45 circus[14844] [ERROR] exception __init__() takes 3 positional arguments but 4 were given caught
```

My circus.ini file is below

```
[circus]
statsd = 1
httpd = 1

[watcher:server]
cmd = "C:\server.exe"
```
The exception seem to be catched so I cannot say where is the error.
I run on Windows 7 64 bits with python 3.6.3

Do you have any hint from were the error come from?

Regards

### PR DESCRIPTION
**Pull request by sboisson**
Fix #1059 #1056

### CODE REVIEW

**Comment by sboisson** [comment]
One failing test is blocking CI checks:

```
======================================================================
ERROR: test_inet6 (circus.tests.test_sockets.TestSockets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/circus-tent/circus/circus/tests/test_sockets.py", line 186, in test_inet6
    sock.bind_and_listen()
  File "/home/travis/build/circus-tent/circus/circus/sockets.py", line 210, in bind_and_listen
    self.bind((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address
-------------------- >> begin captured logging << --------------------
circus: ERROR: Could not bind ::1:0
--------------------- >> end captured logging << ---------------------

```

**Comment by zyv** [comment]
Fix #1030

**Comment by zyv** [comment]
Partially overlaps with #1052.

**Comment by zyv** [comment]
Fixes:

* #1052
* #1064

**Comment by tincho9** [comment]
is this ever going to be merged? :(

**Comment by nd842** [comment]
Merge it please, it's broken out of the box.

**Comment by k4nar** [comment]
Ok let's merge this. I still can't figure out why Travis report those jobs are failed, as all the tests are passing… but whatever.

Sorry for the delay everyone, I'll tag a new release right after.

**Pull request merged**
