### PR TITLE
Find hook plugins relative to config ini

### PR DESCRIPTION
**Pull request by pconerly**
This gives a solution to having relative hooks and plugins, which was brought up in issue https://github.com/circus-tent/circus/issues/867

I've also added some documentation that should help people with #867 

Code review is much appreciated :)

### CODE REVIEW

**Comment by pconerly** [comment]
Locally, I'm having problems with an unrelated test?  Any ideas?

```
test_loggerconfig_default_ini (circus.tests.test_logging.TestLoggingConfig) ...   File "/Users/peterconerly/code/circus/.tox/py26/lib/python2.6/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/Users/peterconerly/code/circus/circus/arbiter.py", line 531, in start
    self.initialize()
  File "/Users/peterconerly/code/circus/circus/util.py", line 479, in _log
    return func(self, *args, **kw)
  File "/Users/peterconerly/code/circus/circus/arbiter.py", line 492, in initialize
    self.evpub_socket.bind(self.pubsub_endpoint)
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5324)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7916)
    raise ZMQError(errno)
```

and on Travis things are also not working. :-/ Investigating...

**Comment by k4nar** [comment]
Thank you for working on that, I think this is a major pain point :) .

However, I've mixed feelings about this approach. One one hand, most people will put their hook next to their .ini at the first try, but on the other hand touching to `sys.modules` seems a bit hazardous.

If someone where to add the config dir to the PYTHONPATH in the env section, would that make the hook importable? If so, I think this should be the official way, and this should be documented.

**Comment by pconerly** [comment]
@k4nar Thanks for taking a look--

I just dove back into the code and I feel like a crap for missing this line: https://github.com/circus-tent/circus/blob/23c0408380d1f0ae832b6c5f37200868d5c824c4/circus/watcher.py#L308-L314

I'm going to add a test and some docs. It's nice that both `PATH` and `PYTHONPATH` will expand things like `$PWD`.

I'm not sure what to do on the plugins side of things though.  Plugins don't have access to `[env:pluginname]`, ([see here](https://github.com/circus-tent/circus/blob/23c0408380d1f0ae832b6c5f37200868d5c824c4/circus/config.py#L273-L276)) so is the solution to give them access to env?

**Comment by pconerly** [comment]
Closing, but I'd love input on what to do with plugins.

**Pull request closed without merging**
