### PR TITLE
Update readthedocs links.

### PR DESCRIPTION
**Pull request by Natim**
r? @k4nar

### CODE REVIEW

**Comment by k4nar** [comment]
I wasn't aware of that change. Actually I can't find any info, have there been any communication around that?

Anyway, r+ :+1:!

**Comment by k4nar** [comment]
By the way as you can see the CI is badly broken. Some tests are almost always failing. I'll try to fix that in the next few weeks, but I might need some help :) .

**Comment by Natim** [comment]
https://twitter.com/readthedocs/status/725468390509277185

**Comment by k4nar** [comment]
Great, thanks!

**Comment by adamchainz** [comment]
I made #985, a dupe with HTTPS, it has been merged 😊

**Comment by k4nar** [comment]
Great thanks!

**Pull request closed without merging**
