### PR TITLE
Updated decrproc and incrproc. Corrected comments

### PR DESCRIPTION
**Pull request by msempere**
@tarekziade fixed all comments in one commit.

### CODE REVIEW

**Comment by k4nar** [comment]
Shouldn't it be "1 being the default" instead of "being 1 the default" ?

**Comment by msempere** [comment]
@k4nar , probably was a mistake in the translation.

**Comment by k4nar** [comment]
Could you make this correction so that we can merge it ?

**Comment by msempere** [comment]
@k4nar should be fixed...right now.

**Comment by k4nar** [comment]
Awesome, thanks.

**Pull request merged**
