### PR TITLE
enable automated deploy to pypi

### PR DESCRIPTION
**Pull request by mrbox**
As states on http://docs.travis-ci.com/user/deployment/pypi/ - you just need to fill username and encrypted password. Then, travis will push to Pypi new version of Chaussette on each tagged commit.

This exactly same PR as https://github.com/circus-tent/chaussette/pull/71, created after suggestion of @k4nar :)

### CODE REVIEW

**Comment by douardda** [comment]
need to check how to do this using credentials from the travis project's variables, as described here 

  http://docs.travis-ci.com/user/environment-variables/#Using-Settings

since there is way these are stored in the public git repository...

**Comment by k4nar** [comment]
@douardda : I don't think we even need those, as the password you put in the `travis.yml` is already encrypted. Either way you rely on Travis security…

**Comment by douardda** [comment]
we discussed about this with @tarekziade a while ago and, IIRC, we agreed not to make travis upload packages to pypi...

**Comment by k4nar** [comment]
Do you have a log of the conversation FTR?

**Comment by k4nar** [comment]
Closing this as we don't want automated releases at the moment.

**Pull request closed without merging**
