### PR TITLE
Added before_reap and after_reap hooks

### PR DESCRIPTION
**Pull request by maingoh**
Related to #1103 
I am not sure if I need to take care of the hook result ?

### CODE REVIEW

**Comment by maingoh** [comment]
Okay, I will update them. I currently ignore the return value of the hook, should I ? I saw that in the code sometimes it is ignored, sometime not.

**Comment by k4nar** [comment]
I think it can be ignored here, yes. We can't do much a bout it :) .

**Comment by k4nar** [comment]
The py26 build failed, but I think we should drop it anyway… Let's carry on.

**Comment by maingoh** [comment]
I had a small question before merging, while testing on my computer, it seems assert* methods where useless. I put a `self.assertTrue(False)` and the test was still passing. Is it only for me ? I misconfigured something ?
Test should pass however (I checked the kwargs by logging it).

**Pull request merged**
