### PR TITLE
Do not allow adding watchers with the same lowercase names

### LINKED ISSUE #936: More problems with watchers when mixing upper and lower cases
#927 fixed the `restart` command but similar issues exist with other commands.

See comment here: https://github.com/circus-tent/circus/issues/927#issuecomment-151531715

### PR DESCRIPTION
**Pull request by biozz**
- add conversion to lowercase when checking for existing watcher
- add test with two watchers foo and Foo, which should raise

Fixes #936

### CODE REVIEW

**Comment by k4nar** [comment]
:+1: 

Could you rebase on master to fix the py34 build?

**Comment by biozz** [comment]
OMG I screwed up this rebase hard... Will try to fix.

**Comment by k4nar** [comment]
At a glance, I would say that your fork's master was not up-to-date with the upstream :) .

**Comment by biozz** [comment]
@k4nar, I managed to fix it, could you please review it?

**Pull request merged**
